@apiUrl = http://localhost:8888/api/admin/orders
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJneXVyY2kwOCIsImV4cCI6MTczNTc1NzI1MywiaWF0IjoxNzM1NzQ3MjUzfQ.44v2dAPl81x4iRdy1efoxgw6InRn_uKa1bKQ_1iNu4A

### Get
GET {{apiUrl}}
Authorization: Bearer {{token}}

### Get Orders with customer name
GET {{apiUrl}}/with-customer-names
Authorization: Bearer {{token}}

### Get Orders with items
GET {{apiUrl}}/with-items
Authorization: Bearer {{token}}

### Create
POST {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "customerId": 1,
  "orderItems": [
    {
      "menuItemId": 1,
      "quantity": 2
    },
    {
      "menuItemId": 2,
      "quantity": 1
    }
  ]
}

### Delete
DELETE {{apiUrl}}
Authorization: Bearer {{token}}