@apiUrl = http://localhost:8888/api
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJneXVyY2kwOCIsImV4cCI6MTczNjEwMjM0NSwiaWF0IjoxNzM2MDkyMzQ1fQ.pN69hB1ghnndsJ_HGzhgZcKcI0RW-11AYo5UqGFwtDI

### Get
GET {{apiUrl}}/admin/users
Authorization: Bearer {{token}}
