@apiUrl = http://localhost:8888/api/auth
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNzM2MDI4NjExLCJpYXQiOjE3MzYwMTg2MTF9.HEXzcbifm6BW9JEectpNjyLtej12ttOtNGvI6WJ2jAs
@refreshToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJneXVyY2kwOCIsImV4cCI6MTczNjM2ODAyMSwiaWF0IjoxNzM1NzYzMjIxfQ.-lYAfrTUTURZOtYLj1I_MtE4JXhsVeExd6kCxbm_3jc

### Login
POST {{apiUrl}}/login
Content-Type: application/json

{
  "username": "test",
  "password": "12345678"
}

### Logout
POST {{apiUrl}}/logout
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "accessToken": "{{token}}",
  "refreshToken": "{{token}}"
}

### Refresh token
POST {{apiUrl}}/refresh
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "refreshToken": "{{refreshToken}}"
}

### Register
POST {{apiUrl}}/register
Content-Type: application/json

{
  "email": "test2@example.com",
  "username": "test2",
  "password": "12345678"
}