@apiUrl = http://localhost:8888/api/auth
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNzM2MTAwNzU5LCJpYXQiOjE3MzYwOTA3NTl9.RQzbAWDjgaAcUvZUb_nO_HTigJcZchypYAv7drcEoIUs
@refreshToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNzM2Njk1NTU5LCJpYXQiOjE3MzYwOTA3NTl9.9yr0v1ZZCxtjYdX4_q9KYQpen52-DS15LYpoCRKMd2Us

### Login
POST {{apiUrl}}/login
Content-Type: application/json

{
  "username": "gyurci08",
  "password": "12345678"
}

### Logout
POST {{apiUrl}}/logout
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "accessToken": "{{token}}",
  "refreshToken": "{{token}}"
}

### Refresh token
POST {{apiUrl}}/refresh
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "refreshToken": "{{refreshToken}}"
}

### Register
POST {{apiUrl}}/register
Content-Type: application/json

{
  "email": "test2@example.com",
  "username": "test2",
  "password": "12345678"
}