@apiUrl = http://localhost:8888/api/customers
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MiIsImV4cCI6MTczNTgxNDM4OSwiaWF0IjoxNzM1ODA0Mzg5fQ.W_xg0S1-fcPYZ7nr8iPvPIAWooYNl16U2lo8lqHZkM0


### MyCustomer
GET {{apiUrl}}
Authorization: Bearer {{token}}


### CreateMyCustomer
POST {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Test User",
  "phone": "1234567890",
  "address": "Hungary, Nowhere, Test Street 2"
}