@apiUrl = http://localhost:8888/api/customers
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNzM2MDI2OTI4LCJpYXQiOjE3MzYwMTY5Mjh9.WgLV-dKCX4JcBkCyLMl04LoaGj6p_G-oSADSBr5HqtM


### MyCustomer
GET {{apiUrl}}
Authorization: Bearer {{token}}


### CreateMyCustomer
POST {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Test User",
  "phone": "1234567890",
  "address": "Hungary, Nowhere, Test Street 2"
}