@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJneXVyY2kwOCIsImV4cCI6MTczNTc0NzAyMiwiaWF0IjoxNzM1NzM3MDIyfQ.k2u_U9RjcXPxJEr-UErN0t6JCB8tqJhdPO-zOzxujLI

### Orders
GET http://localhost:8888/api/orders
Authorization: Bearer {{token}}

### Orders with customer name
GET http://localhost:8888/api/orders/with-customer-names
Authorization: Bearer {{token}}

### Orders with items
GET http://localhost:8888/api/orders/with-items
Authorization: Bearer {{token}}

### Menu items
GET http://localhost:8888/api/menu-items
Authorization: Bearer {{token}}

### Customer
GET http://localhost:8888/api/customers
Authorization: Bearer {{token}}

### Customer
GET http://localhost:8888/api/users
Authorization: Bearer {{token}}
