### GET request to example server
GET http://localhost:8888/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJneXVyY2kwOCIsImV4cCI6MTczNTAzODU3MSwiaWF0IjoxNzM1MDM0OTcxfQ.5QJpAEF7aX9qrGy4m9UoD3bHw9huN9iyaV-eT6kXrbg
