@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJneXVyY2kwOCIsImV4cCI6MTczNjAxNTY4OSwiaWF0IjoxNzM2MDA1Njg5fQ.gzLrP6uP9EEE1o8ylx9dJdo3QfhRBHM4XoofCaL--VU

### Get
GET http://localhost:8888/api/menu-items
Authorization: Bearer {{token}}
