@apiUrl = http://localhost:8888/api/orders
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MiIsImV4cCI6MTczNTgyNDI4NSwiaWF0IjoxNzM1ODE0Mjg1fQ.73fXeA65SSnjHpn9X5QLwWX583PE0MYP6-HwVB_aqtg

### Get
GET {{apiUrl}}
Authorization: Bearer {{token}}

### Get Orders with customer name
GET {{apiUrl}}/with-customer-names
Authorization: Bearer {{token}}

### Get Orders with items
GET {{apiUrl}}/with-items
Authorization: Bearer {{token}}

### Create
POST {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "customerId": 3,
  "orderItems": [
    {
      "menuItemId": 1,
      "quantity": 3
    },
    {
      "menuItemId": 2,
      "quantity": 2
    }
  ]
}

### Delete
DELETE {{apiUrl}}/4
Authorization: Bearer {{token}}