@apiUrl = http://localhost:8888/api/orders
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJneXVyY2kwOCIsImV4cCI6MTczNTg0NTc3NiwiaWF0IjoxNzM1ODM1Nzc2fQ.eiaPb0e355Zp6bj9p_4qkazGVUTUA4sd0DjkUixN5Qk

### Get
GET {{apiUrl}}
Authorization: Bearer {{token}}

### Get Orders with customer name
GET {{apiUrl}}/with-customer-names
Authorization: Bearer {{token}}

### Get Orders with items
GET {{apiUrl}}/with-items
Authorization: Bearer {{token}}

### Create
POST {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "customerId": 3,
  "orderItems": [
    {
      "menuItemId": 1,
      "quantity": 3
    },
    {
      "menuItemId": 2,
      "quantity": 2
    }
  ]
}

### Delete
DELETE {{apiUrl}}/4
Authorization: Bearer {{token}}