@apiUrl = http://localhost:8888/api/orders
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNzM2MDI4OTU2LCJpYXQiOjE3MzYwMTg5NTZ9.tnbHMr6ts56fzmvaIwmcPs7lU4cw9e7w85DHG17PKEYs

### Get
GET {{apiUrl}}
Authorization: Bearer {{token}}

### Create
POST {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "customerId": 3,
  "orderItems": [
    {
      "menuItemId": 1,
      "quantity": 3
    },
    {
      "menuItemId": 2,
      "quantity": 2
    }
  ]
}

### Delete
DELETE {{apiUrl}}/4
Authorization: Bearer {{token}}