@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJneXVyY2kwOCIsImV4cCI6MTczNTc0NzAyMiwiaWF0IjoxNzM1NzM3MDIyfQ.k2u_U9RjcXPxJEr-UErN0t6JCB8tqJhdPO-zOzxujLI

### Get
GET http://localhost:8888/api/orders
Authorization: Bearer {{token}}

### Get Orders with customer name
GET http://localhost:8888/api/orders/with-customer-names
Authorization: Bearer {{token}}

### Get Orders with items
GET http://localhost:8888/api/orders/with-items
Authorization: Bearer {{token}}

### Create
POST http://localhost:8888/api/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "customerId": 1,
  "orderItems": [
    {
      "menuItemId": 1,
      "quantity": 2
    },
    {
      "menuItemId": 2,
      "quantity": 1
    }
  ]
}

### Delete
DELETE http://localhost:8888/api/orders
Authorization: Bearer {{token}}