### POST request to the example server
POST http://localhost:8888/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJneXVyY2kwOCIsImV4cCI6MTczNDUxNjM0MiwiaWF0IjoxNzM0NTEyNzQyfQ.3mgPUYHo1zOVwu-wFIoXyYCA_STFnkJDYbwOaGda4HA"
}