server:
  port: 8888

spring:
  application:
    name: pizzeria


  datasource:
    url: jdbc:postgresql://localhost:5432/pizzeria
    username: pizzeria
    password: 12345678
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml


springdoc:
  api-docs:
    path: /api-docs


cors:
  allowed-origins: http://localhost:4200
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  max-age: 3600

# 3600000  # 1 hour in milliseconds
jwt:
  tokenSecret: sOop-lwzVcoOV1_RE3yKFZ9QR4634T6zc9VLQ3rvZnk=
  tokenExpiration: 60000  # 1 minute in milliseconds
  refreshSecret: sOop-lwzVcoOV1_RE3yKFZ9QR4634T6zc9VLQ3rvZnk=
  refreshExpiration: 604800000  # 7 days in milliseconds

  logging:
    level:
      org:
        springframework:
          jdbc:
            core: debug
      hu:
        jandzsogyorgy: debug
      root: info
